name: GitHub Pages Deploy

on:
  push:
    branches:
      - main
    paths:
      - 'index.html'
      - 'css/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: echo "No build step required"  # Replace if you have a build process
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
